package proxy

import (
	"strings"
	"testing"
)

const goldenTwoStacks = `# Generated by kazi — do not edit.

api.shop.localhost {
	tls internal
	reverse_proxy api.shop:3000
}

blog.localhost {
	tls internal
	reverse_proxy web.blog:8080
}
`

func TestRenderCaddyfile(t *testing.T) {
	routes := []Route{
		{Stack: "blog", Service: "web", Hostname: "blog.localhost", Alias: "web.blog", Port: 8080},
		{Stack: "shop", Service: "api", Hostname: "api.shop.localhost", Alias: "api.shop", Port: 3000},
	}
	got := string(RenderCaddyfile(routes))
	if got != goldenTwoStacks {
		t.Errorf("got:\n%s\nwant:\n%s", got, goldenTwoStacks)
	}
	// same-named services in two stacks dial distinct aliases
	r2 := []Route{
		{Stack: "a", Service: "web", Hostname: "a.localhost", Alias: "web.a", Port: 80},
		{Stack: "b", Service: "web", Hostname: "b.localhost", Alias: "web.b", Port: 80},
	}
	out := string(RenderCaddyfile(r2))
	if !strings.Contains(out, "reverse_proxy web.a:80") || !strings.Contains(out, "reverse_proxy web.b:80") {
		t.Errorf("collision aliases missing:\n%s", out)
	}
}

func TestRenderCaddyfileEmpty(t *testing.T) {
	got := string(RenderCaddyfile(nil))
	if got != "# Generated by kazi — do not edit.\n" {
		t.Errorf("empty render = %q", got)
	}
}
