package proxy

import (
	"fmt"
	"sort"
	"strings"
)

const caddyHeader = "# Generated by kazi — do not edit.\n"

// RenderCaddyfile renders one site block per route, tls internal (Caddy's
// local CA covers *.localhost), dialing the kazi-network alias so two
// stacks with identically-named services never collide.
func RenderCaddyfile(routes []Route) []byte {
	var b strings.Builder
	b.WriteString(caddyHeader)
	sorted := append([]Route(nil), routes...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Hostname < sorted[j].Hostname })
	for _, r := range sorted {
		fmt.Fprintf(&b, "\n%s {\n\ttls internal\n\treverse_proxy %s:%d\n}\n", r.Hostname, r.Alias, r.Port)
	}
	return []byte(b.String())
}
