package proxy

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/thapakazi/kazi/internal/compose"
	"github.com/thapakazi/kazi/internal/runtime"
	"github.com/thapakazi/kazi/internal/store"
)

const (
	StackName     = "kazi-proxy"
	NetworkName   = "kazi"
	ContainerName = "kazi-proxy"
)

const composeYML = `# Generated by kazi — do not edit.
services:
  proxy:
    image: caddy:2-alpine
    container_name: kazi-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/etc/caddy:ro
      - caddy-data:/data
    networks:
      - kazi
volumes:
  caddy-data: {}
networks:
  kazi:
    external: true
`

const caddyfileHeader = "# Generated by kazi — do not edit.\n"

// Dir returns the proxy directory under the config root.
func Dir() string {
	return filepath.Join(store.Root(), "proxy")
}

// EnsureStackFiles writes compose.yml and an initial header-only Caddyfile
// if absent. Idempotent.
func EnsureStackFiles() error {
	dir := Dir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("creating proxy dir: %w", err)
	}

	composePath := filepath.Join(dir, "compose.yml")
	if err := os.WriteFile(composePath, []byte(composeYML), 0o644); err != nil {
		return fmt.Errorf("writing proxy compose.yml: %w", err)
	}

	caddyPath := filepath.Join(dir, "Caddyfile")
	if _, err := os.Stat(caddyPath); os.IsNotExist(err) {
		if err := os.WriteFile(caddyPath, []byte(caddyfileHeader), 0o644); err != nil {
			return fmt.Errorf("writing initial Caddyfile: %w", err)
		}
	}
	return nil
}

// EnsureNetwork ensures the kazi network exists, creating it if needed.
func EnsureNetwork(ctx context.Context, rt runtime.Runtime) error {
	_, err := compose.Output(rt.Cmd(ctx, "network", "inspect", NetworkName))
	if err == nil {
		return nil
	}
	// network missing — create it
	if _, err := compose.Output(rt.Cmd(ctx, "network", "create", NetworkName)); err != nil {
		return fmt.Errorf("creating network %s: %w", NetworkName, err)
	}
	return nil
}

// Sync is the generate→diff→validate→reload loop.
func Sync(ctx context.Context, rt runtime.Runtime, routes []Route, proxyRunning bool) error {
	desired := RenderCaddyfile(routes)

	// Read existing Caddyfile content
	caddyPath := filepath.Join(Dir(), "Caddyfile")
	existing, _ := os.ReadFile(caddyPath)

	unchanged := bytes.Equal(desired, existing)

	// Step 2: unchanged content AND (proxy running OR no routes) → no-op
	if unchanged && (proxyRunning || len(routes) == 0) {
		return nil
	}

	// Step 3: no routes and proxy not running → write file only, never start idle proxy
	if len(routes) == 0 && !proxyRunning {
		if err := EnsureStackFiles(); err != nil {
			return err
		}
		return os.WriteFile(caddyPath, desired, 0o644)
	}

	// Step 4: EnsureStackFiles + EnsureNetwork; write Caddyfile.new
	if err := EnsureStackFiles(); err != nil {
		return err
	}
	if err := EnsureNetwork(ctx, rt); err != nil {
		return err
	}
	newPath := filepath.Join(Dir(), "Caddyfile.new")
	if err := os.WriteFile(newPath, desired, 0o644); err != nil {
		return fmt.Errorf("writing Caddyfile.new: %w", err)
	}

	// Step 5: proxy not running → compose up -d
	if !proxyRunning {
		cmd := rt.ComposeCmd(ctx, StackName, Dir(), nil, "up", "-d")
		if _, err := compose.Output(cmd); err != nil {
			_ = os.Remove(newPath)
			return fmt.Errorf("starting kazi-proxy: %w", err)
		}
	}

	// Step 6: validate inside the container
	validateCmd := rt.Cmd(ctx, "exec", ContainerName, "caddy", "validate",
		"--adapter", "caddyfile", "--config", "/etc/caddy/Caddyfile.new")
	if _, err := compose.Output(validateCmd); err != nil {
		_ = os.Remove(newPath)
		return fmt.Errorf("validating Caddyfile: %w", err)
	}

	// Step 7: rename Caddyfile.new → Caddyfile
	if err := os.Rename(newPath, caddyPath); err != nil {
		return fmt.Errorf("installing Caddyfile: %w", err)
	}

	// Step 8: reload
	reloadCmd := rt.Cmd(ctx, "exec", ContainerName, "caddy", "reload",
		"--adapter", "caddyfile", "--config", "/etc/caddy/Caddyfile")
	if _, err := compose.Output(reloadCmd); err != nil {
		return fmt.Errorf("reloading Caddyfile: %w", err)
	}

	return nil
}

// SystemManifest returns the kazi-proxy Stack manifest (System: true).
func SystemManifest() store.Manifest {
	return store.Manifest{
		APIVersion: "kazi.dev/v1alpha1",
		Kind:       "Stack",
		Metadata: store.Metadata{
			Name: StackName,
		},
		Spec: store.Spec{
			System: true,
			Source: store.Source{
				Compose: filepath.Join(Dir(), "compose.yml"),
			},
		},
	}
}
