package proxy

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/thapakazi/kazi/internal/compose"
	"github.com/thapakazi/kazi/internal/runtime"
	"github.com/thapakazi/kazi/internal/store"
)

const (
	StackName     = "kazi-proxy"
	NetworkName   = "kazi"
	ContainerName = "kazi-proxy"
)

const composeYML = `# Generated by kazi — do not edit.
services:
  proxy:
    image: caddy:2-alpine
    container_name: kazi-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/etc/caddy:ro
      - caddy-data:/data
    networks:
      - kazi
    # Lets static routes reach host-published ports (kazi route). Resolves
    # automatically on Docker Desktop; the mapping is required on Linux.
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  caddy-data: {}
networks:
  kazi:
    external: true
`

// Dir returns the proxy directory under the config root.
func Dir() string {
	return filepath.Join(store.Root(), "proxy")
}

// EnsureStackFiles writes compose.yml and an initial header-only Caddyfile
// if absent. Idempotent.
func EnsureStackFiles() error {
	dir := Dir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("creating proxy dir: %w", err)
	}

	composePath := filepath.Join(dir, "compose.yml")
	if err := os.WriteFile(composePath, []byte(composeYML), 0o644); err != nil {
		return fmt.Errorf("writing proxy compose.yml: %w", err)
	}

	caddyPath := filepath.Join(dir, "Caddyfile")
	if _, err := os.Stat(caddyPath); os.IsNotExist(err) {
		if err := os.WriteFile(caddyPath, []byte(caddyHeader), 0o644); err != nil {
			return fmt.Errorf("writing initial Caddyfile: %w", err)
		}
	}
	return nil
}

// EnsureNetwork ensures the kazi network exists, creating it if needed.
func EnsureNetwork(ctx context.Context, rt runtime.Runtime) error {
	_, err := compose.Output(rt.Cmd(ctx, "network", "inspect", NetworkName))
	if err == nil {
		return nil
	}
	// network missing — create it
	if _, err := compose.Output(rt.Cmd(ctx, "network", "create", NetworkName)); err != nil {
		return fmt.Errorf("creating network %s: %w", NetworkName, err)
	}
	return nil
}

// Sync is the generate→diff→validate→reload loop.
func Sync(ctx context.Context, rt runtime.Runtime, routes []Route, proxyRunning bool) error {
	desired := RenderCaddyfile(routes)

	// Read existing Caddyfile content
	caddyPath := filepath.Join(Dir(), "Caddyfile")
	existing, _ := os.ReadFile(caddyPath)

	unchanged := bytes.Equal(desired, existing)

	// Guard semantics:
	//   unchanged && proxyRunning          → no-op (zero runtime calls)
	//   unchanged && !proxyRunning && routes exist → restart path below
	//                                         (skip validate/reload — caddy reads
	//                                          the current Caddyfile at startup)
	//   no routes && !proxyRunning         → write file only (never start idle proxy)
	if unchanged && proxyRunning {
		return nil
	}

	// No routes and proxy not running → ensure dir exists and write file only.
	// Do NOT call EnsureStackFiles: that would clobber compose.yml unnecessarily.
	if len(routes) == 0 && !proxyRunning {
		if err := os.MkdirAll(Dir(), 0o755); err != nil {
			return fmt.Errorf("creating proxy dir: %w", err)
		}
		return os.WriteFile(caddyPath, desired, 0o644)
	}

	// Routes exist (possibly unchanged content but proxy is down) — full start/update path.

	// Step 4: EnsureStackFiles + EnsureNetwork; write Caddyfile.new (or Caddyfile directly if unchanged)
	if err := EnsureStackFiles(); err != nil {
		return err
	}
	if err := EnsureNetwork(ctx, rt); err != nil {
		return err
	}

	// Step 5: proxy not running → attempt compose up -d.
	if !proxyRunning {
		// Write the desired Caddyfile to disk before starting the proxy.
		// This ensures the config is persisted even if compose up fails
		// (e.g. ports 80/443 already bound on the host).  Caddy reads this
		// file at startup, so if unchanged we can return immediately after a
		// successful up; if changed we fall through to validate+reload.
		if !unchanged {
			if err := os.WriteFile(caddyPath, desired, 0o644); err != nil {
				return fmt.Errorf("writing Caddyfile: %w", err)
			}
		}
		cmd := rt.ComposeCmd(ctx, StackName, Dir(), nil, "up", "-d")
		if _, err := compose.Output(cmd); err != nil {
			return fmt.Errorf("starting kazi-proxy: %w", err)
		}
		// Content is already on disk (unchanged) or was just written (changed).
		// Caddy reads the Caddyfile at startup — no validate/reload needed.
		// If content changed we still need to reload a live caddy, so fall
		// through when unchanged only.
		if unchanged {
			return nil
		}
	}

	// Step 6: write Caddyfile.new for validate+reload+rename (content changed path).
	// We keep the new config in Caddyfile.new until both validate AND reload
	// succeed so that a mid-flight failure never leaves disk out of sync with
	// what live caddy is serving.
	newPath := filepath.Join(Dir(), "Caddyfile.new")
	if err := os.WriteFile(newPath, desired, 0o644); err != nil {
		return fmt.Errorf("writing Caddyfile.new: %w", err)
	}

	// Step 7: validate inside the container (reads Caddyfile.new via the bind-mount).
	validateCmd := rt.Cmd(ctx, "exec", ContainerName, "caddy", "validate",
		"--adapter", "caddyfile", "--config", "/etc/caddy/Caddyfile.new")
	if _, err := compose.Output(validateCmd); err != nil {
		_ = os.Remove(newPath)
		return fmt.Errorf("validating Caddyfile: %w", err)
	}

	// Step 8: reload caddy directly from Caddyfile.new — BEFORE renaming.
	// If reload fails the live caddy is still serving the old config, and
	// Caddyfile on disk still holds the old content.  Removing Caddyfile.new
	// on failure ensures the next Sync sees a diff and retries.
	reloadCmd := rt.Cmd(ctx, "exec", ContainerName, "caddy", "reload",
		"--adapter", "caddyfile", "--config", "/etc/caddy/Caddyfile.new")
	if _, err := compose.Output(reloadCmd); err != nil {
		_ = os.Remove(newPath)
		return fmt.Errorf("reloading Caddyfile: %w", err)
	}

	// Step 9: reload succeeded — promote Caddyfile.new → Caddyfile so disk
	// reflects the config that caddy is now serving.
	if err := os.Rename(newPath, caddyPath); err != nil {
		return fmt.Errorf("installing Caddyfile: %w", err)
	}

	return nil
}

// SystemManifest returns the kazi-proxy Stack manifest (System: true).
func SystemManifest() store.Manifest {
	return store.Manifest{
		APIVersion: "kazi.dev/v1alpha1",
		Kind:       "Stack",
		Metadata: store.Metadata{
			Name: StackName,
		},
		Spec: store.Spec{
			System: true,
			Source: store.Source{
				Compose: filepath.Join(Dir(), "compose.yml"),
			},
		},
	}
}
